# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 11f1c5f3d35a5434969d23caf301d37ab2dd33f69e925371095e824f4a5d92e910c35b00d5bb57996df8b05d53dc3577bacf87ff0e931b8fda7b009242d9fe1f

test:
  secret_key_base: 9df4d0f77976df3b44469730e32958edaedb973b0b263c0f930fda11a4f921b6f2c609be5118691bf5dbb06fca536662f7224c4f1ab433176fdd0f7280a725e9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
